import {
  INVITE_CODE_MAX_LENGTH,
  INVITE_CODE_MIN_LENGTH,
  INVITE_CODE_PATTERN,
} from "@/lib/invites/constants";

/**
 * Alphabet excludes ambiguous 0/O/1/l/I.
 * Must stay aligned with public.generate_outlaw_invite_code().
 */
export const INVITE_CODE_ALPHABET =
  "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";

export function isValidInviteCodeFormat(value: string): boolean {
  const trimmed = value.trim();
  return (
    trimmed.length >= INVITE_CODE_MIN_LENGTH &&
    trimmed.length <= INVITE_CODE_MAX_LENGTH &&
    INVITE_CODE_PATTERN.test(trimmed)
  );
}

export function normalizeInviteCode(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!isValidInviteCodeFormat(trimmed)) return null;
  return trimmed;
}

/** Pure URL-safety check for codes generated by the alphabet. */
export function isUrlSafeInviteCode(code: string): boolean {
  if (!isValidInviteCodeFormat(code)) return false;
  // No reserved URL characters — alphanumeric only.
  return !/[^A-Za-z0-9]/.test(code);
}
